### ISSUE TITLE
Video preview images

### ISSUE THREAD

**Issue by Dhaulagiri** [Dhaulagiri/climbingnarc-videos#10]
These are kind of important...

**Comment by Dhaulagiri** [comment]
This works, but it would ideal if the index page only displayed thumbnails and not videos that could be played

**Comment by xdumaine** [comment]
This could probably leverage the image preview url logic in ember-lazy-load, and wouldn't necessarily have to change the json-api.

**Comment by Dhaulagiri** [comment]
My thought here was that on an index page that lists several videos I didn't want the thumbnails there to allow the videos to be played. I wanted users to have to navigate to the individual video's page to view it. I sort of got around this by wrapping the embeds in links to a specific video, but this doesn't seem ideal. 

I agree this is not an api issue.
