### ISSUE TITLE
Auto embed of videos

### ISSUE THREAD

**Issue by Dhaulagiri** [Dhaulagiri/climbingnarc-videos#3]

**Comment by Dhaulagiri** [comment]
This is working pending my PR getting accepted in ember-lazy-video

**Comment by xdumaine** [comment]
I didn't see this before my PR #15. [Here](https://github.com/poteto/ember-lazy-video/pull/8/files) is the PR @Dhaulagiri mentioned above, doing essentially the same thing, but within the lazy-video component. Let me know if you'd prefer to wait for that PR to go through, and if so, feel free to close #15.

**Comment by Dhaulagiri** [comment]
This is working now
